apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend-deployment
  labels:
    app: notes-frontend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: notes-frontend
  template:
    metadata:
      labels:
        app: notes-frontend
    spec:
      containers:
      - name: notes-frontend
        image: ssobol/notes-frontend:${VERSION}  
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
