apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: notes-backend
          image: docker.io/library/notes-backend:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_BASE_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORDE